# Generated by Django 5.2.7 on 2025-11-04 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activaties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(default='', max_length=260)),
                ('is_activate_done', models.BooleanField(default=False)),
                ('activate_type', models.CharField(choices=[('TK', 'Task'), ('HT', 'Habit')], max_length=6)),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
